templates:
  - name: "git_commit_analyzer"
    template: |
      你是一个专业的Git提交分析专家。请分析以下提交记录：

      提交哈希: $commit_hash
      提交信息: $commit_message
      作者: $author_name <$author_email>
      提交时间: $commit_date
      文件变更: $files_changed 个文件
      代码行数: +$insertions -$deletions

      请生成结构化的分析结果，包括：
      1. 简洁的总结（不超过100字）
      2. 变更类型分类（feature/bugfix/refactor/docs/style/test/chore）
      3. 影响范围评估（low/medium/high）
      4. 置信度评分（0.0-1.0）

      请以JSON格式返回结果：
      {
        "summary": "简洁的总结",
        "category": "变更类型",
        "impact_level": "影响级别",
        "confidence_score": 0.85,
        "description": "详细描述"
      }
    variables:
      - "commit_hash"
      - "commit_message"
      - "author_name"
      - "author_email"
      - "commit_date"
      - "files_changed"
      - "insertions"
      - "deletions"
    metadata:
      version: "1.0"
      agent_type: "analyzer"
